path: /content/drive/MyDrive/DsPCBSD+
train: /content/drive/MyDrive/DsPCBSD+/Data_YOLO/images/train
val: /content/drive/MyDrive/DsPCBSD+/Data_YOLO/images/val

names:
  0: short
  1: spur
  2: spurious copper
  3: open
  4: mouse bite
  5: hole breakout
  6: conductor scratch
  7: conductor foreign object
  8: base material foreign object